;
;Copyright 2025–2026 Francenir Inc.
;Copyright 2025–2026 DroidPureC Kernel Inc.
;
;Licensed under the Apache License, Version 2.0 (the "License");
;you may not use this file except in compliance with the License.
;You may obtain a copy of the License at:
;       http://www.apache.org/licenses/LICENSE-2.0
;
#define STACK_SIZE 4096
stack: .space STACK_SIZE

#if defined(CONFIG_X86)
#define STACK_TOP 0x800000
#else
#define STACK_TOP 0x100000
#endif
